CREATE TABLE "attachments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "attachments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"type" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "attachments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "loadout_attachments" (
	"loadout_id" integer NOT NULL,
	"weapon_id" integer NOT NULL,
	"attachment_id" integer NOT NULL,
	CONSTRAINT "loadout_attachments_pkey" PRIMARY KEY("loadout_id","weapon_id","attachment_id")
);
--> statement-breakpoint
CREATE TABLE "weapon_attachments" (
	"weapon_id" integer NOT NULL,
	"attachment_id" bigint NOT NULL,
	CONSTRAINT "weapon_attachments_pkey" PRIMARY KEY("weapon_id","attachment_id")
);
--> statement-breakpoint
ALTER TABLE "weapon_attachments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "gadgets" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "loadouts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "operator_gadgets" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "operator_weapons" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "operators" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "weapons" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "profiles" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "profiles" CASCADE;--> statement-breakpoint
ALTER TABLE "loadouts" DROP CONSTRAINT "loadouts_user_id_users_id_fk";
--> statement-breakpoint
ALTER TABLE "loadouts" ALTER COLUMN "user_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "operators" ADD COLUMN "icon_url" text;--> statement-breakpoint
ALTER TABLE "operators" ADD COLUMN "portrait_url" text;--> statement-breakpoint
ALTER TABLE "gadgets" ADD COLUMN "icon_url" text;--> statement-breakpoint
ALTER TABLE "loadouts" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "loadouts" ADD COLUMN "name" text DEFAULT '';--> statement-breakpoint
ALTER TABLE "loadout_attachments" ADD CONSTRAINT "loadout_attachments_attachment_id_fkey" FOREIGN KEY ("attachment_id") REFERENCES "public"."attachments"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "loadout_attachments" ADD CONSTRAINT "loadout_attachments_loadout_id_fkey" FOREIGN KEY ("loadout_id") REFERENCES "public"."loadouts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "loadout_attachments" ADD CONSTRAINT "loadout_attachments_weapon_id_fkey" FOREIGN KEY ("weapon_id") REFERENCES "public"."weapons"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "weapon_attachments" ADD CONSTRAINT "weapon_attachments_attachment_id_fkey" FOREIGN KEY ("attachment_id") REFERENCES "public"."attachments"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "weapon_attachments" ADD CONSTRAINT "weapon_attachments_weapon_id_fkey" FOREIGN KEY ("weapon_id") REFERENCES "public"."weapons"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "operators" DROP COLUMN "image_url";--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "operators" AS PERMISSIVE FOR SELECT TO public USING (true);--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "gadgets" AS PERMISSIVE FOR SELECT TO public USING (true);--> statement-breakpoint
CREATE POLICY "Users must insert their own tasks" ON "loadouts" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((( SELECT (auth.jwt() ->> 'sub'::text)) = user_id));--> statement-breakpoint
CREATE POLICY "User can view their own tasks" ON "loadouts" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "weapons" AS PERMISSIVE FOR SELECT TO public USING (true);--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "operator_gadgets" AS PERMISSIVE FOR SELECT TO public USING (true);--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "operator_weapons" AS PERMISSIVE FOR SELECT TO public USING (true);--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "attachments" AS PERMISSIVE FOR SELECT TO public USING (true);--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "weapon_attachments" AS PERMISSIVE FOR SELECT TO public USING (true);