import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import localFont from "next/font/local";
import { Navbar } from "@/components/Navbar";
import { Theme } from "@/providers/Theme";
import Footer from "@/components/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-Inter" });

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-Poppins",
});

const ScoutBoldItalic = localFont({
  src: "../fonts/ScoutCond-BoldItalic.otf",
  variable: "--font-ScoutCond-BoldItalic",
});
const ScoutBold = localFont({
  src: "../fonts/ScoutCond-Bold.otf",
  variable: "--font-ScoutCond-Bold",
});

export const metadata: Metadata = {
  title: "Ultimate Siegery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${poppins.variable} ${ScoutBoldItalic.variable} ${ScoutBold.variable}`}
      >
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
